sudo: false
language: python
python: 3.5
env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=lint
branches:
  only:
  - master
before_install: travis_retry pip install twine "pip>=8.0" tox
script: tox -e $TOX_ENV
