sudo: false
language: python
python: 3.5
env:
- TOX_ENV=py27
- TOX_ENV=py35
- TOX_ENV=flake8
branches:
  only:
  - master
before_install: travis_retry pip install twine "pip>=8.0" tox
script: tox -e $TOX_ENV
deploy:
  provider: pypi
  user: peterbe
  password:
    secure: WY0RRfx+bKDlTWzVZaqwFly7Rp4S1a86hMMmJ5bzhJkstMNmQXBKwowr7KnYQiqdIRQgVz4UXR/jb2mZFaa6aqJG+UUvX0w8zl57PZ5FkHHKiILOxx986dG03lszNL4Npg29iGSgrg3KLFpufsQR1HB/leTSqVe/Hj50dTwFpXGpvB79k0fgn9m8ZwYtPdKFu+ed4syVL8yZ8RLkVdQ/Qy9t4YysOm/Z8zXzrRCOr5nt0XGXOMyhUMmhVwf1vfTj8eVSa1QrnJIn6zA9VOzdbdlregfL89DCMQdxyKzcpJqP0iDdGia2248pwQYVrkV018vpWtuqo/UAMwqhp6ajochbX5fABRtVx0N9b89LhJcRhFtg3SKpaG5MbaFuyHVhlSCn8on36K+bGZ5VksKk7GbEIpF33vSlxDjEwa3CsC2wqNMM6K5Xy04k16WH2FZNRTXejmuNeRlN9V5sk7jd2/FRrZ2TzrBEpOsxqeCCvdyjAT0FBPdVUmiNMtElLHRZdJmjaPtEXWiLn8jPBiPEfVZs0AdBTrh/6KG2FiG8mNordVmNFZwBc90UyqZGLzT1+jzd5Wof5iLVF1hF+6ErSxXdPWfJLWpRLpilMzZesbAJwHFdg2vH+pSUbm14ZKhRChocp/1VEROor3HXkHzVgMed29askKa76NxpitVYYjs=
  distributions: sdist bdist_wheel
  on:
    repo: peterbe/json-schema-reducer
